name: Release

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: Whether to run semantic-release in `dry-run` mode
        type: boolean
        required: true
        default: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          semantic_version: 18.0.0
          dry_run: ${{ inputs.dry_run }}
          #@semantic-release/changelog@6.0.0
          extra_plugins: |
            @semantic-release/git@10.0.0
            conventional-changelog-conventionalcommits@4.6.3
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_PAT }}
