name: Release

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: Whether to run semantic-release in `dry-run` mode
        type: boolean
        required: true
        default: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      DEBUG: semantic-release:*
    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
        with:
          persist-credentials: false
          fetch-depth: 0
      
#      Uncomment when not using github action to run semantic-release
      # - name: Setup Node
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '>=20'

      - name: Node version
        run: node --version

      - name: Release
        uses: cycjimmy/semantic-release-action@cb425203a562475bca039ba4dbf90c7f9ac790f4 # v4.1.0
        with:
          semantic_version: 23.0.2
          dry_run: ${{ inputs.dry_run }}
          extra_plugins: |
            @semantic-release/changelog@6.0.3
            @semantic-release/git@10.0.1
            conventional-changelog-conventionalcommits@7.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_PAT }}
